name: CI clang

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y liblz4-dev liblz4-1
        sudo apt-get install -y libzstd-dev libzstd1
        sudo apt-get install -y libssl-dev libssl3

    - name: build
      run: |
        make CC=clang
        make clean

    - name: build with lz4
      run: |
        make COMPRESS_LZ4=1 CC=clang
        make clean

    - name: build with zstd
      run: |
        make COMPRESS_ZSTD=1 CC=clang
        make clean

    - name: build with md5
      run: |
        make CHECKSUM_MD5=1 CC=clang
        make clean

    - name: build with enc
      run: |
        make ENCRYPT=1 CC=clang
        make clean

    - name: build with lz4 zstd md5 enc
      run: |
        make COMPRESS_LZ4=1 COMPRESS_ZSTD=1 CHECKSUM_MD5=1 ENCRYPT=1 CC=clang
        make clean
